name: Team Deployment

on:
  workflow_run:
    workflows: ["Build and Upload"]
    types:
      - completed

jobs:
  kimiko-golang:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    environment:
      name: "kimiko-golang"
      url: ${{ vars.URL }}

    steps:
      - name: Deploy to kimiko-golang environment
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd hng_boilerplate_nextjs
            ./scripts/team_deploy.sh kimiko-golang ${{ vars.PORT }}
            
  kimiko-csharp:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    environment:
      name: "kimiko-csharp"
      url: ${{ vars.URL }}

    steps:
      - name: Deploy to kimiko-csharp environment
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd hng_boilerplate_nextjs
            ./scripts/team_deploy.sh kimiko-csharp ${{ vars.PORT }}

  anchor-java:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    environment:
      name: "anchor-java"
      url: ${{ vars.URL }}

    steps:
      - name: Deploy to anchor-java environment
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd hng_boilerplate_nextjs
            ./scripts/team_deploy.sh anchor-java ${{ vars.PORT }}

  anchor-python:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    environment:
      name: "anchor-python"
      url: ${{ vars.URL }}

    steps:
      - name: Deploy to anchor-python environment
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd hng_boilerplate_nextjs
            ./scripts/team_deploy.sh anchor-python ${{ vars.PORT }}

  bulldozer-php:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    environment:
      name: "bulldozer-php"
      url: ${{ vars.URL }}

    steps:
      - name: Deploy to bulldozer-php environment
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd hng_boilerplate_nextjs
            ./scripts/team_deploy.sh bulldozer-php ${{ vars.PORT }}

  starlight-nestjs:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    environment:
      name: "starlight-nestjs"
      url: ${{ vars.URL }}

    steps:
      - name: Deploy to starlight-nestjs environment
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd hng_boilerplate_nextjs
            ./scripts/team_deploy.sh starlight-nestjs ${{ vars.PORT }}

  panther-expressjs:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    environment:
      name: "panther-expressjs"
      url: ${{ vars.URL }}

    steps:
      - name: Deploy to panther-expressjs environment
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd hng_boilerplate_nextjs
            ./scripts/team_deploy.sh panther-expressjs ${{ vars.PORT }}
